[package]
name = "lnk"
version = "0.1.0"
authors = ["Lily Hopkins <bsalarius@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "~1.2"
byteorder = "~1.3"
num-traits = "0.2"
num-derive = "0.2"
